# Copyright (C) CampusIoT,  - All Rights Reserved
# Written by CampusIoT Dev Team, 2016-2018

version: "2"

services:
  loraserver:
    image: loraserver/loraserver:2
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  appserver:
    image: loraserver/lora-app-server:2
    ports:
      - 443:8080
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server

  gatewaybridge:
    image: loraserver/lora-gateway-bridge:2
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/lora-gateway-bridge:/etc/lora-gateway-bridge

  geoserver:
    image: loraserver/lora-geo-server:2
    volumes:
      - ./configuration/lora-geo-server:/etc/lora-geo-server

  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    volumes:
      - ./data/redis:/data

  mosquitto:
    extends:
      file: mosquitto.yml
      service: mosquitto

  postgres-backup-ns:
    extends:
      file: pgbackup.yml
      service: postgres-backup-ns
    links:
      - postgresql:db # Maps postgres as "db"

  postgres-backup-as:
    extends:
      file: pgbackup.yml
      service: postgres-backup-as
    links:
      - postgresql:db # Maps postgres as "db"

  mqtt-logger:
    extends:
      file: mqtt-logger.yml
      service: mqtt-logger
