version: "2"

services:
  pgadmin:
    links:
      - postgresql:postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adming@campusiot.org
      PGADMIN_DEFAULT_PASSWORD: SUPER_SECRET_TO_CHANGE
    volumes:
       - ./configuration/postgresql/pgadmin:/root/.pgadmin
    ports:
      - 3080:80
    restart: unless-stopped

  influxdb:
    image: influxdb
    volumes:
       - ./configuration/influxdb:/var/lib/influxdb
       - ./data/influxdb:/data
    ports:
      - 8086:8086
      - 8083:8083
    restart: unless-stopped

  nodered:
    build:
      context: ./docker/nodered
    image: campusiot/nodered:latest
    #image: nodered/node-red-docker
    links:
      - influxdb:influxdb
    environment:
      NODE_OPTIONS: --max_old_space_size=128
      FLOWS: flow.json
    volumes:
       - ./configuration/nodered:/data
    ports:
      - 1880:1880
    restart: unless-stopped

# http://docs.grafana.org/installation/docker/
  grafana:
    image: grafana/grafana
    links:
      - influxdb:influxdb
    environment:
      GF_SECURITY_ADMIN_PASSWORD: SUPER_SECRET_TO_CHANGE
      #GF_SERVER_ROOT_URL: http://grafana.server.name
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
       - ./configuration/grafana/:/var/lib/grafana/
    ports:
      - 3000:3000
    restart: unless-stopped

  chronograf:
    image: chronograf
    links:
      - influxdb:influxdb
    environment:
      GF_SECURITY_ADMIN_PASSWORD: SUPER_SECRET_TO_CHANGE
      FLOWS: flow.json
    volumes:
       - ./configuration/chronograf:/var/lib/chronograf
    ports:
      - 8888:8888
    restart: unless-stopped

  telegraf:
    image: telegraf
    links:
      - influxdb:influxdb
    volumes:
       - ./configuration/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
       - ./data/telegraf:/data
    restart: unless-stopped

  kapacitor:
    image: kapacitor
    links:
      - influxdb:influxdb
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_LOGGING_LEVEL: INFO
      #KAPACITOR_REPORTING_ENABLED: false
      KAPACITOR_INFLUXDB_0_URLS_0: http://loraserver-docker_influxdb_1:8086
    volumes:
       - ./configuration/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
       - ./data/kapacitor:/var/lib/kapacitor
    ports:
      - 9092:9092
    restart: unless-stopped

# https://devopsheaven.com/letsencrypt/devops/docker/nginx/https/www/seo/2017/09/01/letsencrypt-certificates-nginx.html
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./configuration/nginx/html:/usr/share/nginx/html:ro

# https://github.com/istepanov/docker-pg_dump
# https://devopsheaven.com/postgresql/pg_dump/databases/docker/backup/2017/09/10/backup-postgresql-database-using-docker.html
# TODO pgdump:

# https://hub.docker.com/r/superitman/fail2ban/
# TODO fail2ban:

# https://hub.docker.com/r/diouxx/glpi/
# TODO glpi:
  glpi:
    image: diouxx/glpi
    ports:
      - 2080:80
    #volumes:
    #  - ./configuration/nginx/html:/usr/share/nginx/html:ro
    # link: yourdatabase:mysql
