# Copyright (C) CampusIoT,  - All Rights Reserved
# Written by CampusIoT Dev Team, 2016-2018

# From https://github.com/uibkops/fail2ban

version: '2'

services:

  fail2ban_as:
    image: fail2ban:latest
    container_name: fail2ban
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #Examples for jails and filters can be found at fail2ban website or within the container
      #- ./jail.d/guacamole.conf:/etc/fail2ban/jail.d/guacamole.conf
      #- ./filter.d/guacamole:/etc/fail2ban/filterd./guacamole
      #mount some log volumes here
      - ./logs/guacamole:/var/log/tomcat

#   fail2ban_bridge:
#   fail2ban_grafana:
#   fail2ban_nodered:
#   fail2ban_gateway_manager:
