# Copyright (C) CampusIoT,  - All Rights Reserved
# Written by CampusIoT Dev Team, 2016-2018

version: "2"

services:
  mosquitto:
    build:
      context: ./docker/mosquitto
    image: campusiot/mosquitto:latest
#    image: eclipse-mosquitto
#    environment:
#      PGID: campusiot
#      PUID: campusiot
    volumes:
       - ./configuration/mosquitto/config/:/mosquitto/config/
       - ./configuration/mosquitto/certs/:/etc/mosquitto/certs/
    ports:
      - 1883:1883 # Plain MQTT
      - 8883:8883 # MQTT over TLS/SSL
      - 9001:9001 # Plain WebSockets
      - 8081:9883 # WebSockets over TLS/SSL
