version: "2"

services:
  mqtt-logger:
    image: campusiot/mqtt-logger:latest
#    links:
#      - mqtt-1:moquitto
    volumes:
      - ./data/mqtt-logger/msg.log:/usr/src/app/msg.log:rw
#       - ./configuration/mqtt-logger/settings.json:/usr/src/app/settings.json:ro
    restart: unless-stopped
