# Copyright (C) CampusIoT,  - All Rights Reserved
# Written by CampusIoT Dev Team, 2016-2018

version: "2"

services:

  postgres-backup:
    image: annixa/docker-pg_dump
    container_name: postgres-backup
    links:
      - postgresql:db #Maps postgres as "db"
    environment:
      - PGUSER=loraserver_as
      - PGPASSWORD=loraserver_as
      - CRON_SCHEDULE=* * * * * # Every minute
      - DELETE_OLDER_THAN=10080 # ten days : Optionally delete files older than $DELETE_OLDER_THAN minutes.
      - PGDB=loraserver_as # The name of the database to dump
    #  - PGHOST=db # The hostname of the PostgreSQL database to dump
    volumes:
      - ./backups/postgresql:/dump
    command: dump-cron
