FROM nodered/node-red-docker
MAINTAINER CampusIoT didier.donsez@gmail.com

RUN npm install node-red-contrib-influxdb
RUN npm install node-red-contrib-pubnub
RUN npm install node-red-contrib-ifttt
RUN npm install node-red-dashboard
RUN npm install node-red-contrib-web-worldmap

# RUN npm install node-red-node-mongodb
# RUN npm install node-red-contrib-kafka-node
